name: example
description: "A PUI gallery example app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  gap: ^3.0.1
  go_router: ^13.2.0
  layout: ^1.0.5
  material_symbols_icons: ^4.2719.1
  pui:
    path: ../
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
