name: pui
description: "PITR's Flutter UI Theme"
version: 0.0.1
homepage: https://github.com/PITR-DEV/PUI

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  gap: ^3.0.1
  go_router: ^13.2.0
  layout: ^1.0.5
  open_simplex_2: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/JetBrainsMono/JetBrainsMono[wght].ttf
        - asset: assets/JetBrainsMono/JetBrainsMono-Italic[wght].ttf
          style: italic
  assets:
    - assets/noise/noise_4096_colored.png
    - assets/noise/noise_4096_monochrome.png
