name: pui
description: "A minimal Material 3-based theme and components for Flutter, developed by PITR."
version: 0.0.6
homepage: https://github.com/PITR-DEV/PUI

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dynamic_color: ^1.8.1
  fast_immutable_collections: ^11.0.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  go_router: 16.1.0
  layout: ^1.0.5
  material_symbols_icons: ^4.2858.1
  open_simplex_2: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono[wght].ttf
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Italic[wght].ttf
          style: italic
    - family: Albert Sans
      fonts:
        - asset: assets/fonts/AlbertSans/AlbertSans-VariableFont_wght.ttf
        - asset: assets/fonts/AlbertSans/AlbertSans-Italic-VariableFont_wght.ttf
          style: italic
  assets:
    - assets/noise/noise_256_colored.webp
    - assets/noise/noise_256_monochrome.webp
